// flow-typed signature: 15b6a98a52cda550ad40ca11607c1774
// flow-typed version: <<STUB>>/add-variable-declarations_v^3.1.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'add-variable-declarations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'add-variable-declarations' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'add-variable-declarations/src/index' {
  declare module.exports: any;
}

declare module 'add-variable-declarations/src/types' {
  declare module.exports: any;
}

declare module 'add-variable-declarations/src/utils/buildDeclarationForNames' {
  declare module.exports: any;
}

declare module 'add-variable-declarations/src/utils/flatMap' {
  declare module.exports: any;
}

declare module 'add-variable-declarations/src/utils/getBindingIdentifiersFromLHS' {
  declare module.exports: any;
}

declare module 'add-variable-declarations/src/utils/getFirstStatementInBlock' {
  declare module.exports: any;
}

declare module 'add-variable-declarations/src/utils/getIndentForLineContainingOffset' {
  declare module.exports: any;
}

declare module 'add-variable-declarations/src/utils/getParenthesesRanges' {
  declare module.exports: any;
}

declare module 'add-variable-declarations/src/utils/lhsHasNonIdentifierAssignment' {
  declare module.exports: any;
}

declare module 'add-variable-declarations/src/utils/TraverseState' {
  declare module.exports: any;
}

// Filename aliases
declare module 'add-variable-declarations/src/index.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/index'>;
}
declare module 'add-variable-declarations/src/types.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/types'>;
}
declare module 'add-variable-declarations/src/utils/buildDeclarationForNames.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/utils/buildDeclarationForNames'>;
}
declare module 'add-variable-declarations/src/utils/flatMap.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/utils/flatMap'>;
}
declare module 'add-variable-declarations/src/utils/getBindingIdentifiersFromLHS.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/utils/getBindingIdentifiersFromLHS'>;
}
declare module 'add-variable-declarations/src/utils/getFirstStatementInBlock.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/utils/getFirstStatementInBlock'>;
}
declare module 'add-variable-declarations/src/utils/getIndentForLineContainingOffset.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/utils/getIndentForLineContainingOffset'>;
}
declare module 'add-variable-declarations/src/utils/getParenthesesRanges.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/utils/getParenthesesRanges'>;
}
declare module 'add-variable-declarations/src/utils/lhsHasNonIdentifierAssignment.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/utils/lhsHasNonIdentifierAssignment'>;
}
declare module 'add-variable-declarations/src/utils/TraverseState.js' {
  declare module.exports: $Exports<'add-variable-declarations/src/utils/TraverseState'>;
}
