// flow-typed signature: 3a09de872540c3c266a4b80bfd06d092
// flow-typed version: <<STUB>>/eslint-plugin-local-rules_v^0.1.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-local-rules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-local-rules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-plugin-local-rules/index' {
  declare module.exports: $Exports<'eslint-plugin-local-rules'>;
}
declare module 'eslint-plugin-local-rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-local-rules'>;
}
