// flow-typed signature: a6098f392be9209cec313e311661d742
// flow-typed version: <<STUB>>/mobx-react-router_v^4.0.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-react-router/dist/mobx-react-router' {
  declare module.exports: any;
}

declare module 'mobx-react-router/dist/mobx-react-router.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-react-router/dist/mobx-react-router.js' {
  declare module.exports: $Exports<'mobx-react-router/dist/mobx-react-router'>;
}
declare module 'mobx-react-router/dist/mobx-react-router.min.js' {
  declare module.exports: $Exports<'mobx-react-router/dist/mobx-react-router.min'>;
}
